<Head>
  <link
    rel="preload"
    href="../public/fonts/RobotoMono-VariableFont_wght.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
  <link
    rel="preload"
    href="../public/fonts/Outfit-VariableFont_wght.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
  <link
    rel="preload"
    href="../public/fonts/Manrope-VariableFont_wght.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
</Head>;
